services:
  - type: web
    name: esp32-sensor-backend
    env: node
    region: singapore
    plan: free
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MQTT_BROKER
        sync: false
      - key: MQTT_PORT
        sync: false
      - key: MQTT_USERNAME
        sync: false
      - key: MQTT_PASSWORD
        sync: false
      - key: MQTT_CLIENT_ID
        sync: false
      - key: MQTT_TOPIC
        sync: false
